"""Capa de dominio: value objects, entidades, eventos y contratos de repositorios.

Esta capa NO depende de ninguna librería de infraestructura (ni SQLAlchemy ni Qt).
Reglas de negocio e invariantes viven aquí.
"""

from app.domain.value_objects import Money
from app.domain.entities import (
    Apartado,
    ApartadoAbono,
    ApartadoItem,
    CashDay,
    CashMovement,
    Category,
    Payment,
    PaymentMethod,
    Product,
    Sale,
    SaleItem,
    StockMovement,
)
from app.domain.events import (
    ApartadoAbonado,
    ApartadoCancelled,
    ApartadoCreated,
    ApartadoSettled,
    CashDayClosed,
    CashDayOpened,
    CashMovementRegistered,
    DomainEvent,
    LowStockAlert,
    SaleCompleted,
    SaleItemRefunded,
    SaleVoided,
    StockAdjusted,
)
from app.domain.repositories import (
    ApartadoRepository,
    CashDayRepository,
    CashMovementRepository,
    CategoryRepository,
    ProductRepository,
    SaleRepository,
    StockMovementRepository,
)
from app.domain.exceptions import (
    ApartadoNotFoundError,
    CashDayAlreadyOpenError,
    CashDayAlreadyClosedError,
    CategoryNotFoundError,
    DomainError,
    DuplicateProductCodeError,
    InsufficientStockError,
    InvalidQuantityError,
    NoOpenCashDayError,
    ProductNotFoundError,
    SaleAlreadyVoidedError,
    SaleItemRefundError,
    SaleNotFoundError,
    ValidationError,
)

__all__ = [
    "Money",
    "Apartado",
    "ApartadoAbono",
    "ApartadoItem",
    "CashDay",
    "CashMovement",
    "Category",
    "Payment",
    "PaymentMethod",
    "Product",
    "Sale",
    "SaleItem",
    "StockMovement",
    "ApartadoAbonado",
    "ApartadoCancelled",
    "ApartadoCreated",
    "ApartadoSettled",
    "CashDayClosed",
    "CashDayOpened",
    "CashMovementRegistered",
    "DomainEvent",
    "LowStockAlert",
    "SaleCompleted",
    "SaleItemRefunded",
    "SaleVoided",
    "StockAdjusted",
    "ApartadoRepository",
    "CashDayRepository",
    "CashMovementRepository",
    "CategoryRepository",
    "ProductRepository",
    "SaleRepository",
    "StockMovementRepository",
    "ApartadoNotFoundError",
    "CashDayAlreadyOpenError",
    "CashDayAlreadyClosedError",
    "CategoryNotFoundError",
    "DomainError",
    "DuplicateProductCodeError",
    "InsufficientStockError",
    "InvalidQuantityError",
    "NoOpenCashDayError",
    "ProductNotFoundError",
    "SaleAlreadyVoidedError",
    "SaleItemRefundError",
    "SaleNotFoundError",
    "ValidationError",
]